version: "3.8"

services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-laravel-app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8001:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      test-db:
        condition: service_healthy
    networks:
      - test-network

  test-db:
    image: mariadb:11.5
    container_name: test-laravel-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: laravel_test
      MARIADB_USER: laravel
      MARIADB_PASSWORD: secret
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - test-dbdata:/var/lib/mysql
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  test-dbdata:
